/*
 * SPDX-FileCopyrightText: 2020 DB Station&Service AG <bahnhoflive-opensource@deutschebahn.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package de.deutschebahn.bahnhoflive.backend.wagenstand.istwr.model;

import java.util.List;

public class WagenstandAllFahrzeugData {

    public List<WagenstandAllFahrzeugausstattungData> allFahrzeugausstattung; // "allFahrzeugausstattung":[],
    public String kategorie;                //"kategorie":"STEUERWAGENERSTEKLASSE",
    public String fahrzeugnummer;           //"fahrzeugnummer":"938054110706",
    public String orientierung;             //"orientierung":"UNDEFINIERT",
    public String positioningruppe;         //"positioningruppe":"1",
    public String fahrzeugsektor;           //"fahrzeugsektor":"D",
    public String fahrzeugtyp;              //"fahrzeugtyp":"Apmzf",
    public String wagenordnungsnummer;      //"wagenordnungsnummer":"28",
    public WagenstandPositionAmhaltData positionamhalt;//"positionamhalt":{"endemeter":"237.2","endeprozent":"59","startmeter":"209.3","startprozent":"52"},
    public String status;                   //    "status":"OFFEN"

    public interface Category {

        String LOK = "LOCOMOTIVE"; //LOK";

        String TRIEBKOPF = "POWERCAR"; //TRIEBKOPF
        String STEUERWAGENERSTEKLASSE = "CONTROLCAR_FIRST_CLASS"; //"STEUERWAGENERSTEKLASSE";
        String STEUERWAGENZWEITEKLASSE = "CONTROLCAR_ECONOMY_CLASS"; //"STEUERWAGENZWEITEKLASSE";
        String STEUERWAGENERSTEZWEITEKLASSE = "CONTROLCAR_FIRST_ECONOMY_CLASS"; //"STEUERWAGENERSTEZWEITEKLASSE";

        String DOPPELSTOCKSTEUERWAGENERSTEKLASSE = "DOUBLEDECK_CONTROLCAR_FIRST_CLASS"; //"DOPPELSTOCKSTEUERWAGENERSTEKLASSE";
        String DOPPELSTOCKSTEUERWAGENZWEITEKLASSE = "DOUBLEDECK_CONTROLCAR_ECONOMY_CLASS"; //"DOPPELSTOCKSTEUERWAGENZWEITEKLASSE";
        String DOPPELSTOCKSTEUERWAGENERSTEZWEITEKLASSE = "DOUBLEDECK_CONTROLCAR_FIRST_ECONOMOY_CLASS"; //"DOPPELSTOCKSTEUERWAGENERSTEZWEITEKLASSE";

        String REISEZUGWAGENERSTEZWEITEKLASSE = "PASSENGERCARRIAGE_FIRST_ECONOMY_CLASS"; //"REISEZUGWAGENERSTEZWEITEKLASSE";
        String REISEZUGWAGENZWEITEKLASSE = "PASSENGERCARRIAGE_ECONOMY_CLASS"; //"REISEZUGWAGENZWEITEKLASSE";
        String REISEZUGWAGENERSTEKLASSE = "PASSENGERCARRIAGE_FIRST_CLASS"; //"REISEZUGWAGENERSTEKLASSE";
        String DOPPELSTOCKWAGENERSTEZWEITEKLASSE = "DOUBLEDECK_FIRST_ECONOMY_CLASS"; //"DOPPELSTOCKWAGENERSTEZWEITEKLASSE";
        String DOPPELSTOCKWAGENERSTEKLASSE = "DOUBLEDECK_FIRST_CLASS"; //"DOPPELSTOCKWAGENERSTEKLASSE";
        String DOPPELSTOCKWAGENZWEITEKLASSE = "DOUBLEDECK_ECONOMY_CLASS"; // "DOPPELSTOCKWAGENZWEITEKLASSE";

        String SPEISEWAGEN = "DININGCAR"; //"SPEISEWAGEN";
        String HALBSPEISEWAGENZWEITEKLASSE = "HALFDININGCAR_ECONOMY_CLASS"; //"HALBSPEISEWAGENZWEITEKLASSE";
        String HALBSPEISEWAGENERSTEKLASSE = "HALFDININGCAR_FIRST_CLASS"; //"HALBSPEISEWAGENERSTEKLASSE";

        String SCHLAFWAGENERSTEKLASSE = "SLEEPER_FIRST_CLASS"; //"SCHLAFWAGENERSTEKLASSE";
        String SCHLAFWAGENERSTEZWEITEKLASSE = "SLEEPER_FIRST_ECONOMY_CLASS"; //"SCHLAFWAGENERSTEZWEITEKLASSE";
        String SCHLAFWAGENZWEITEKLASSE = "SLEEPER_ECONOMY_CLASS"; //"SCHLAFWAGENZWEITEKLASSE";
        String LIEGEWAGENERSTEKLASSE = "COUCHETTE_FIRST_CLAS"; //"LIEGEWAGENERSTEKLASSE";
        String LIEGEWAGENZWEITEKLASSE = "COUCHETTE_ECONOMY_CLASS"; //"LIEGEWAGENZWEITEKLASSE";

        String GEPAECKWAGEN = "BAGGAGECAR"; // "GEPAECKWAGEN";

        String DOPPELSTOCKAUTOTRANSPORTWAGENREISEZUGWAGENBAUART = "DOUBLEDECK_CARCARRIER_PASSENGERTRAIN"; // "DOPPELSTOCKAUTOTRANSPORTWAGENREISEZUGWAGENBAUART";

        String DOPPELSTEUERWAGENERSTEKLASSE = "DOUBLECONTROLCAR_FIRST_ECONOMY_CLASS";
        String DOPPELSTEUERWAGENZWEITEKLASSE = "DOUBLECONTROLCAR_ECONOMY_CLASS";
        String UNBEKANNT = "UNDEFINED";

    }
}
